# Generated by Django 3.2 on 2024-11-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva3', '0002_auto_20241031_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='partido',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='eva3.Comentario'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='logolocal',
            field=models.ImageField(upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='logovisita',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
