# Generated by Django 3.2 on 2024-11-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva3', '0003_auto_20241031_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='comentarios',
        ),
    ]
