# Generated by Django 3.2 on 2024-11-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva3', '0004_remove_partido_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='horapartido',
            field=models.TimeField(),
        ),
    ]
