# Generated by Django 3.2 on 2024-11-01 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eva3', '0005_alter_partido_horapartido'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eva3.partido'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partido',
            name='logolocal',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='logovisita',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
